# -*- coding: utf-8 -*-
"""Home

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g_yDLYGEvD9tkwx4_ey85Oxmg61RHjCg
"""

import streamlit as st

st.set_page_config(page_title="User Registration System", layout="wide")

st.markdown("<h1 style='text-align: center;'>Welcome to Registration System</h1>", unsafe_allow_html=True)

col1, col2, col3 = st.columns([1, 1, 1])
with col2:
    st.markdown("""
    <div style="display: flex; justify-content: center; margin-bottom: 30px;">
        <div style="width: 100px; height: 100px; background-color: black; border-radius: 50%;"></div>
    </div>
    """, unsafe_allow_html=True)

col1, col2, col3 = st.columns([1, 2, 1])
with col2:
    st.page_link("1_Registration.py", label="Begin Registration Process", icon="📝")
