# -*- coding: utf-8 -*-
"""pages/2_Documents

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JP9C5AKew5oI5OypTU34hD0TKXBp_nuW
"""

import streamlit as st

st.set_page_config(page_title="Upload Documents", layout="wide")

if 'documents' not in st.session_state:
    st.session_state['documents'] = {
        'id_card': None,
        'passport': None,
        'work_permit': None,
        'visa': None
    }

st.markdown("<h1 style='text-align: center;'>Upload Documents</h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align: center;'>Please upload the required documents</p>", unsafe_allow_html=True)

st.session_state['documents']['id_card'] = st.file_uploader("Upload ID Card", type=["jpg", "jpeg", "png", "pdf"])
st.session_state['documents']['passport'] = st.file_uploader("Upload Passport", type=["jpg", "jpeg", "png", "pdf"])
st.session_state['documents']['work_permit'] = st.file_uploader("Upload Work Permit", type=["jpg", "jpeg", "png", "pdf"])
st.session_state['documents']['visa'] = st.file_uploader("Upload Visa", type=["jpg", "jpeg", "png", "pdf"])

st.page_link("pages/3_Verification.py", label="Continue to Verification", icon="✅")