# -*- coding: utf-8 -*-
"""pages/3_Verification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eFz5daKVcDtri4JO5dYi7D8ZuffQNShK
"""

import streamlit as st
import time

st.set_page_config(page_title="Verification Process", layout="wide")

if 'verification_status' not in st.session_state:
    st.session_state['verification_status'] = 'pending'

st.markdown("<h1 style='text-align: center;'>Verification Process</h1>", unsafe_allow_html=True)

st.info("Your documents are being verified. Please wait...")

progress_bar = st.progress(0)
for i in range(100):
    time.sleep(0.05)
    progress_bar.progress(i + 1)

st.session_state['verification_status'] = 'approved'
st.success("Verification completed!")

st.page_link("pages/4_Profile.py", label="View Your Profile", icon="👤")